grails-profiles/base

- skeleton/build.gradle
- skeleton/grails-app/conf/application.yml
- skeleton/grails-app/conf/logback.groovy
It also switches off banner printing via configuration
> Adds coloured output support by default

- features/hibernate4/skeleton/grails-app/conf/application.yml
- features/hibernate5/skeleton/grails-app/conf/application.yml
Closes https://github.com/grails-plugins/grails-spring-security-core/issues/494
> disable use_second_level_cache

- features/hibernate4/skeleton/grails-app/conf/application.yml
- features/hibernate5/skeleton/grails-app/conf/application.yml
Reverts grails-profiles/base#9
> Revert "disable use_second_level_cache"

- features/asset-pipeline/feature.yml
- features/hibernate5/feature.yml
- features/json-views/feature.yml
- features/less-asset-pipeline/feature.yml
- features/markup-views/feature.yml
Upgrade:
- asset-pipeline
- Hibernate5
- grails-views
To latest versions
> Upgrade dependencies

- skeleton/gradle.properties
Resolves https://github.com/grails/grails-core/issues/11374
> Add jvmarg to fix i18n on Windows/pathingJar=true

- profile.yml
Close: https://github.com/grails/grails-core/issues/11503
> add micronaut-inject-groovy as testcompile also

- build.gradle
- gradle.properties
> Bump Grails Gradle Plugin from 4.0.11-2 to 5.0.0.M1

- .github/dependabot.yml
- .github/workflows/gradle.yml
- .github/workflows/release-notes.yml
> Update Github Workflows

- features/asset-pipeline/feature.yml
- features/less-asset-pipeline/feature.yml
> Bump asset-pipeline from 3.2.4 to 3.3.1

- features/geb2/feature.yml
> Bump Selenium from 3.14.0 to 3.141.59

- features/hibernate5/feature.yml
> Bump Glassfish el-impl from 2.1.2-b03 to 2.2.1-b05

- profile.yml
- skeleton/gradle.properties
> Decouple grails-gradle-plugin from grailsVersion property

- features/hibernate5/feature.yml
> Correct hibernate-core version from 5.5.7 to 5.5.7.Final

- features/json-views/feature.yml
- features/markup-views/feature.yml
> Update Grails Views to 2.1.1

- skeleton/grails-app/conf/application.yml
Reverts grails-profiles/base#80
> Revert "Set Spring allow-circular-references: true to avoid breaking change"

- skeleton/settings.gradle
Fixes grails/grails-core#12268
> Update appName placeholder key

- commands/run-app.groovy
- commands/stop-app.groovy
- skeleton/grails-app/conf/application.yml
Because spring management endpoints was changed, and shutdown was disabled default.
See related grails issue here: https://github.com/grails/grails-core/issues/12377
> Grails stop app error in interactive mode

- commands/stats.groovy
> Add java helper, test classes to stats

- features/json-views/feature.yml
- features/markup-views/feature.yml
> Update Grails Views to 2.3.2

- features/mongodb/feature.yml
Fixes grails/grails-core#12727
> Change scope for embedded-mongodb plugin
